root = "."
tmp_dir = ".dest"

[build]
  cmd = "go build -o ./.dest/server src/main.go"
  bin = "./.dest/server"
  include_ext = ["go"]
  exclude_dir = [".dest"]
  kill_delay = "1s"

[proxy]
  enabled = true